### PR TITLE
OSD-7599

### PR DESCRIPTION
**Pull request by robotmaxtron**
Boilerplate update including https://github.com/openshift/boilerplate/pull/188 for v1 CRDs.

### CODE REVIEW

**Review by fahlmant — APPROVED** [review]
/lgtm

**Comment by 2uasimojo** [comment]
The changes in #57 aren't needed to make this work. We should just land that PR separately.

Otherwise this lgtm, clean bp update.

**Comment by robotmaxtron** [comment]
Just the boilerplate update now, I'll use the boilerplate update scripts moving forward.

**Review by fahlmant — APPROVED** [review]
/lgtm

**Pull request merged**
