### PR TITLE
Remove obsolete targets and hack/ artifacts

### PR DESCRIPTION
**Pull request by 2uasimojo**
The hack scripts are no longer used since cutting over to boilerplate.

The make targets were scrubbed via
https://github.com/openshift/release/pull/12961.

The manifests are not used or referenced anywhere. Possibly made
obsolete by boilerplate, or even before that.

### CODE REVIEW

**Comment by fahlmant** [comment]
Be careful here. We found that cloud-ingress-operator still needed some of these scripts to generate the SSS needed in the olm-artifacts-template.yaml

**Comment by 2uasimojo** [comment]
> Be careful here. We found that cloud-ingress-operator still needed some of these scripts to generate the SSS needed in the olm-artifacts-template.yaml

Mm, noted. I did test the appsre pipeline for mgo with this change and everything is copacetic. But please cast your eyes upon https://github.com/openshift/boilerplate/pull/197 -- I don't *think* CIO needs that stuff, but it's worth checking.

**Comment by csheremeta** [comment]
@fahlmant I don't see anything being ripped out here that hasn't also been ripped out of CIO

**Pull request merged**
