### PR TITLE
Update boilerplate

### PR DESCRIPTION
**Pull request by NautiluX**
* Side-effect: Fixing e2e tests as 2 versions with CRD v1 will exist

### CODE REVIEW

**Comment by jharrington22** [comment]
/lgtm

cc/ @dustman9000

**Comment by dustman9000** [comment]
The boilerplate update looks fine, but it seems to only contain the podman vs docker support. It looks like MGO already has the boilerplate update to support v1 vs v1beta1 CRDs.

**Comment by jharrington22** [comment]
@dustman9000 thats correct but it breaks the osde2e tests when they do an n -1 test since the commit before doesn't have the V1 CRD.

**Pull request merged**
